[package]
name = "node_reqwest"
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
core = { workspace = true }
mimalloc = { workspace = true }
neon = { workspace = true }

[build-dependencies]
anyhow.workspace = true
meta = { workspace = true }
neon-build = { workspace = true }
