[package]
name = "node_reqwest"
edition.workspace = true

[lints]
workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
mimalloc = { workspace = true }
neon = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }

[build-dependencies]
anyhow.workspace = true
meta = { workspace = true }
